AllCops:
  Exclude:
    - 'Rakefile'
    - 'Guardfile'
    - '*.gemspec'
    - '**/*.rake'
  
Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'